aws_access_key_id: 'AKIAJ5VZMSXUUBS7A4HQ'
aws_secret_access_key: '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'
address: 'smtp.gmail.com'
port: 587
domain: 'gmail.com'
user_name: 'martamanzanaro'
password: 'zeusfaber'