#!/usr/bin/env ruby
# rails runner script/initial_admin_user

u = User.new({:email => "jtcarpenter@gmail.com", :password => "B1gD4y", :password_confirmation => "B1gD4y", :admin => true }).save(:validate => false)
